<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="9" ignored="16" total="40" passed="15">
  <reporter-output>
  </reporter-output>
  <suite name="KT" duration-ms="10619" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:42 IST">
    <groups>
    </groups>
    <test name="CTC" duration-ms="10619" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:42 IST">
      <class name="KTCTC.FIRSTMAVENProject.DependentTestCases">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.DependentTestCases@1563da5]" name="beforeClass" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="verfyNewUserCanBeAddedToSystem()[pri:0, instance:KTCTC.FIRSTMAVENProject.DependentTestCases@1563da5]" name="verfyNewUserCanBeAddedToSystem" duration-ms="3" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyNewUserCanBeAddedToSystem -->
        <test-method status="PASS" signature="beforeMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.DependentTestCases@1563da5]" name="beforeMethodAnnotation" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodAnnotation -->
        <test-method status="PASS" signature="afterMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.DependentTestCases@1563da5]" name="afterMethodAnnotation" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodAnnotation -->
        <test-method status="PASS" signature="beforeMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.DependentTestCases@1563da5]" name="beforeMethodAnnotation" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodAnnotation -->
        <test-method status="FAIL" signature="verfyExistingUserCanBeEdited()[pri:0, instance:KTCTC.FIRSTMAVENProject.DependentTestCases@1563da5]" name="verfyExistingUserCanBeEdited" duration-ms="1" started-at="2021-12-17T22:00:42 IST" depends-on-methods="KTCTC.FIRSTMAVENProject.DependentTestCases.verfyNewUserCanBeAddedToSystem" finished-at="2021-12-17T22:00:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at KTCTC.FIRSTMAVENProject.DependentTestCases.verfyExistingUserCanBeEdited(DependentTestCases.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyExistingUserCanBeEdited -->
        <test-method status="PASS" signature="afterMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.DependentTestCases@1563da5]" name="afterMethodAnnotation" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodAnnotation -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.DependentTestCases@1563da5]" name="afterClass" is-config="true" duration-ms="2" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- KTCTC.FIRSTMAVENProject.DependentTestCases -->
      <class name="KTCTC.FIRSTMAVENProject.DataPRoviderInTestNG">
        <test-method status="FAIL" signature="getUserData(java.lang.String, java.lang.String)[pri:0, instance:KTCTC.FIRSTMAVENProject.DataPRoviderInTestNG@34cd072c]" name="getUserData" duration-ms="0" started-at="2021-12-17T22:00:32 IST" data-provider="keyValue" finished-at="2021-12-17T22:00:32 IST">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void KTCTC.FIRSTMAVENProject.DataPRoviderInTestNG.getUserData(java.lang.String,java.lang.String) requires a @DataProvider named : keyValue]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void KTCTC.FIRSTMAVENProject.DataPRoviderInTestNG.getUserData(java.lang.String,java.lang.String) requires a @DataProvider named : keyValue
at org.testng.internal.Parameters.findDataProvider(Parameters.java:559)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserData -->
        <test-method status="PASS" signature="verifyAdultPlaBotFlow()[pri:0, instance:KTCTC.FIRSTMAVENProject.DataPRoviderInTestNG@34cd072c]" name="verifyAdultPlaBotFlow" duration-ms="733" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAdultPlaBotFlow -->
        <test-method status="FAIL" signature="verifyChildPlaBotFlow()[pri:0, instance:KTCTC.FIRSTMAVENProject.DataPRoviderInTestNG@34cd072c]" name="verifyChildPlaBotFlow" duration-ms="79" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at KTCTC.FIRSTMAVENProject.BotAuto.checkBotFlow(BotAuto.java:16)
at KTCTC.FIRSTMAVENProject.DataPRoviderInTestNG.verifyChildPlaBotFlow(DataPRoviderInTestNG.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyChildPlaBotFlow -->
      </class> <!-- KTCTC.FIRSTMAVENProject.DataPRoviderInTestNG -->
      <class name="KTCTC.FIRSTMAVENProject.PriorityInTestNG">
        <test-method status="PASS" signature="verfyNewUserCanBeAddedToSystem()[pri:1, instance:KTCTC.FIRSTMAVENProject.PriorityInTestNG@458c1321]" name="verfyNewUserCanBeAddedToSystem" duration-ms="8" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyNewUserCanBeAddedToSystem -->
        <test-method status="PASS" signature="verfyNewUserCanBeAddedToSystem()[pri:1, instance:KTCTC.FIRSTMAVENProject.PriorityInTestNG@458c1321]" name="verfyNewUserCanBeAddedToSystem" duration-ms="2" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyNewUserCanBeAddedToSystem -->
        <test-method status="FAIL" signature="verfyNewUserCanBeAddedToSystem()[pri:1, instance:KTCTC.FIRSTMAVENProject.PriorityInTestNG@458c1321]" name="verfyNewUserCanBeAddedToSystem" duration-ms="2" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at KTCTC.FIRSTMAVENProject.PriorityInTestNG.verfyNewUserCanBeAddedToSystem(PriorityInTestNG.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyNewUserCanBeAddedToSystem -->
        <test-method status="PASS" signature="verfyNewUserCanBeAddedToSystem()[pri:1, instance:KTCTC.FIRSTMAVENProject.PriorityInTestNG@458c1321]" name="verfyNewUserCanBeAddedToSystem" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyNewUserCanBeAddedToSystem -->
        <test-method status="PASS" signature="verfyExistingUserCanBeEdited()[pri:203, instance:KTCTC.FIRSTMAVENProject.PriorityInTestNG@458c1321]" name="verfyExistingUserCanBeEdited" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyExistingUserCanBeEdited -->
        <test-method status="PASS" signature="verfyExistingUserCanBeDeleted()[pri:56, instance:KTCTC.FIRSTMAVENProject.PriorityInTestNG@458c1321]" name="verfyExistingUserCanBeDeleted" duration-ms="8" started-at="2021-12-17T22:00:32 IST" depends-on-methods="KTCTC.FIRSTMAVENProject.PriorityInTestNG.verfyExistingUserCanBeEdited" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyExistingUserCanBeDeleted -->
      </class> <!-- KTCTC.FIRSTMAVENProject.PriorityInTestNG -->
      <class name="KTCTC.FIRSTMAVENProject.AssertionsInTestNG">
        <test-method status="FAIL" signature="methodAFromAssertionsInTestNG()[pri:0, instance:KTCTC.FIRSTMAVENProject.AssertionsInTestNG@5faeada1]" name="methodAFromAssertionsInTestNG" duration-ms="1" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Current share pricce is not displayed as per requirement expected [44] but found [44]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Current share pricce is not displayed as per requirement expected [44] but found [44]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at KTCTC.FIRSTMAVENProject.AssertionsInTestNG.methodAFromAssertionsInTestNG(AssertionsInTestNG.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodAFromAssertionsInTestNG -->
        <test-method status="FAIL" signature="methodBFromAssertionsInTestNG()[pri:0, instance:KTCTC.FIRSTMAVENProject.AssertionsInTestNG@5faeada1]" name="methodBFromAssertionsInTestNG" duration-ms="1" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Still message is displayed on UI expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Still message is displayed on UI expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at KTCTC.FIRSTMAVENProject.AssertionsInTestNG.methodBFromAssertionsInTestNG(AssertionsInTestNG.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodBFromAssertionsInTestNG -->
      </class> <!-- KTCTC.FIRSTMAVENProject.AssertionsInTestNG -->
      <class name="KTCTC.FIRSTMAVENProject.FIleUploadTestCase">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.FIleUploadTestCase@7a1ebcd8]" name="beforeClass" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.FIleUploadTestCase@7a1ebcd8]" name="beforeMethodAnnotation" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodAnnotation -->
        <test-method status="PASS" signature="verfyUserCanUploadFileSuccessfully()[pri:0, instance:KTCTC.FIRSTMAVENProject.FIleUploadTestCase@7a1ebcd8]" name="verfyUserCanUploadFileSuccessfully" duration-ms="9611" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyUserCanUploadFileSuccessfully -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:KTCTC.FIRSTMAVENProject.FIleUploadTestCase@7a1ebcd8]" name="afterMethod" is-config="true" duration-ms="3" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verfyUserCanUploadFileSuccessfully status=SUCCESS method=FIleUploadTestCase.verfyUserCanUploadFileSuccessfully()[pri:0, instance:KTCTC.FIRSTMAVENProject.FIleUploadTestCase@7a1ebcd8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.FIleUploadTestCase@7a1ebcd8]" name="afterMethodAnnotation" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodAnnotation -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.FIleUploadTestCase@7a1ebcd8]" name="afterClass" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- KTCTC.FIRSTMAVENProject.FIleUploadTestCase -->
      <class name="KTCTC.FIRSTMAVENProject.InvocationCount">
        <test-method status="PASS" signature="verfyExistingUserCanBeDeleted()[pri:0, instance:KTCTC.FIRSTMAVENProject.InvocationCount@ea1a8d5]" name="verfyExistingUserCanBeDeleted" duration-ms="3" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyExistingUserCanBeDeleted -->
        <test-method status="FAIL" signature="verfyExistingUserCanBeEdited()[pri:0, instance:KTCTC.FIRSTMAVENProject.InvocationCount@ea1a8d5]" name="verfyExistingUserCanBeEdited" duration-ms="1" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at KTCTC.FIRSTMAVENProject.InvocationCount.verfyExistingUserCanBeEdited(InvocationCount.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyExistingUserCanBeEdited -->
      </class> <!-- KTCTC.FIRSTMAVENProject.InvocationCount -->
      <class name="KTCTC.FIRSTMAVENProject.SoftAssertionsInTestNG">
        <test-method status="FAIL" signature="methodAFromAssertionsInTestNG()[pri:0, instance:KTCTC.FIRSTMAVENProject.SoftAssertionsInTestNG@528931cf]" name="methodAFromAssertionsInTestNG" duration-ms="4" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Current share pricce is not displayed as per requirement expected [44] but found [44],
Upload file message is not displayed corret expected [1 File uploaded successfully] but found [ File uploaded successfully],
Inbox text is not displayed.. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Current share pricce is not displayed as per requirement expected [44] but found [44],
Upload file message is not displayed corret expected [1 File uploaded successfully] but found [ File uploaded successfully],
Inbox text is not displayed.. expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at KTCTC.FIRSTMAVENProject.SoftAssertionsInTestNG.methodAFromAssertionsInTestNG(SoftAssertionsInTestNG.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodAFromAssertionsInTestNG -->
        <test-method status="FAIL" signature="methodBFromAssertionsInTestNG()[pri:0, instance:KTCTC.FIRSTMAVENProject.SoftAssertionsInTestNG@528931cf]" name="methodBFromAssertionsInTestNG" duration-ms="4" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Current share pricce is not displayed as per requirement expected [44] but found [44],
Upload file message is not displayed corret expected [1 File uploaded successfully] but found [ File uploaded successfully],
Inbox text is not displayed.. expected [true] but found [false],
Still message is displayed on UI expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Current share pricce is not displayed as per requirement expected [44] but found [44],
Upload file message is not displayed corret expected [1 File uploaded successfully] but found [ File uploaded successfully],
Inbox text is not displayed.. expected [true] but found [false],
Still message is displayed on UI expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at KTCTC.FIRSTMAVENProject.SoftAssertionsInTestNG.methodBFromAssertionsInTestNG(SoftAssertionsInTestNG.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodBFromAssertionsInTestNG -->
      </class> <!-- KTCTC.FIRSTMAVENProject.SoftAssertionsInTestNG -->
      <class name="KTCTC.FIRSTMAVENProject.Annotation2">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.Annotation2@11438d26]" name="beforeClass" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="methodAFromAnnotation2()[pri:0, instance:KTCTC.FIRSTMAVENProject.Annotation2@11438d26]" name="methodAFromAnnotation2" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodAFromAnnotation2 -->
        <test-method status="PASS" signature="beforeMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.Annotation2@11438d26]" name="beforeMethodAnnotation" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodAnnotation -->
        <test-method status="PASS" signature="afterMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.Annotation2@11438d26]" name="afterMethodAnnotation" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodAnnotation -->
        <test-method status="PASS" signature="beforeMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.Annotation2@11438d26]" name="beforeMethodAnnotation" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodAnnotation -->
        <test-method status="PASS" signature="methodBFromAnnotation2()[pri:0, instance:KTCTC.FIRSTMAVENProject.Annotation2@11438d26]" name="methodBFromAnnotation2" duration-ms="2" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodBFromAnnotation2 -->
        <test-method status="PASS" signature="afterMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.Annotation2@11438d26]" name="afterMethodAnnotation" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodAnnotation -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.Annotation2@11438d26]" name="afterClass" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- KTCTC.FIRSTMAVENProject.Annotation2 -->
      <class name="KTCTC.FIRSTMAVENProject.AnnotationsInTestNG">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="beforeSuite" is-config="true" duration-ms="8" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="beforeTest" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="beforeClass" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="beforeMethodAnnotation" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodAnnotation -->
        <test-method status="PASS" signature="VerifyUserCanLoginWithValidUserNameAndValidPassword()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="VerifyUserCanLoginWithValidUserNameAndValidPassword" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanLoginWithValidUserNameAndValidPassword -->
        <test-method status="PASS" signature="afterMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="afterMethodAnnotation" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodAnnotation -->
        <test-method status="PASS" signature="beforeMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="beforeMethodAnnotation" is-config="true" duration-ms="3" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodAnnotation -->
        <test-method status="PASS" signature="VerifyUserCanNotLoginWithInValidUserNameAndValidPassword()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="VerifyUserCanNotLoginWithInValidUserNameAndValidPassword" duration-ms="2" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanNotLoginWithInValidUserNameAndValidPassword -->
        <test-method status="PASS" signature="afterMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="afterMethodAnnotation" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodAnnotation -->
        <test-method status="PASS" signature="beforeMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="beforeMethodAnnotation" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodAnnotation -->
        <test-method status="PASS" signature="VerifyUserCanNotLoginWithValidUserNameAndInValidPassword()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="VerifyUserCanNotLoginWithValidUserNameAndInValidPassword" duration-ms="2" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserCanNotLoginWithValidUserNameAndInValidPassword -->
        <test-method status="PASS" signature="afterMethodAnnotation()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="afterMethodAnnotation" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodAnnotation -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="afterClass" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:32 IST" finished-at="2021-12-17T22:00:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="afterTest" is-config="true" duration-ms="1" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:KTCTC.FIRSTMAVENProject.AnnotationsInTestNG@305fd85d]" name="afterSuite" is-config="true" duration-ms="0" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- KTCTC.FIRSTMAVENProject.AnnotationsInTestNG -->
      <class name="KTCTC.FIRSTMAVENProject.EnableClass">
        <test-method status="PASS" signature="methodBFromEnableClass()[pri:0, instance:KTCTC.FIRSTMAVENProject.EnableClass@2bbf4b8b]" name="methodBFromEnableClass" duration-ms="2" started-at="2021-12-17T22:00:42 IST" finished-at="2021-12-17T22:00:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodBFromEnableClass -->
      </class> <!-- KTCTC.FIRSTMAVENProject.EnableClass -->
    </test> <!-- CTC -->
  </suite> <!-- KT -->
</testng-results>
